"""created opening column

Revision ID: ab086731d6e7
Revises: 
Create Date: 2023-03-09 14:37:45.017849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab086731d6e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moves', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ecocode', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openings_id'), 'openings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_openings_id'), table_name='openings')
    op.drop_table('openings')
    # ### end Alembic commands ###
